export enum ErrorCodes {
    DB_ERROR = 'DB_ERROR', 
    INPUT_ERROR = "INPUT_ERROR",
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_REQUEST_BEARER_MISSING = "INVALID_REQUEST_BEARER_MISSING",
    ALREADY_EXIST = "ALREADY_EXISTS"
}